version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  app:
    build: .
    ports:
      - "3000:3000"
    command: yarn start
    depends_on:
      - mongo
      - redis
    volumes:
      - ".:/app"
